name: CI/CD for Python Package

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  package:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel twine

      - name: Build the package
        run: |
          python setup.py sdist bdist_wheel  # Build the source and wheel distribution

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}  # Set this in your repository secrets
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}  # Set this in your repository secrets
        run: |
          twine upload dist/*  # Upload the package to PyPI
