name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies and Run unit tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_workflow.txt
          pip install .
          pytest --cov=frml --cov-report=html
