name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  CI-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install pytest and Run unit tests
        run: |
          uv pip install .
          pytest --cov=frml --cov-report=html
